select * from tbl_challenge



INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 01', 'm_pwd 01', 'm_name 01', 'm_nick 01', 'm_phone 01', 'm_email 01', sysdate, 'N', 'm_job 01', 'm_addr 01', sysdate, 01, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 02', 'm_pwd 02', 'm_name 02', 'm_nick 02', 'm_phone 02', 'm_email 02', sysdate, 'N', 'm_job 02', 'm_addr 02', sysdate, 02, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 03', 'm_pwd 03', 'm_name 03', 'm_nick 03', 'm_phone 03', 'm_email 03', sysdate, 'N', 'm_job 03', 'm_addr 03', sysdate, 03, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 04', 'm_pwd 04', 'm_name 04', 'm_nick 04', 'm_phone 04', 'm_email 04', sysdate, 'N', 'm_job 04', 'm_addr 04', sysdate, 04, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 05', 'm_pwd 05', 'm_name 05', 'm_nick 05', 'm_phone 05', 'm_email 05', sysdate, 'N', 'm_job 05', 'm_addr 05', sysdate, 05, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 06', 'm_pwd 06', 'm_name 06', 'm_nick 06', 'm_phone 06', 'm_email 06', sysdate, 'N', 'm_job 06', 'm_addr 06', sysdate, 06, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 07', 'm_pwd 07', 'm_name 07', 'm_nick 07', 'm_phone 07', 'm_email 07', sysdate, 'N', 'm_job 07', 'm_addr 07', sysdate, 07, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 08', 'm_pwd 08', 'm_name 08', 'm_nick 08', 'm_phone 08', 'm_email 08', sysdate, 'N', 'm_job 08', 'm_addr 08', sysdate, 08, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 09', 'm_pwd 09', 'm_name 09', 'm_nick 09', 'm_phone 09', 'm_email 09', sysdate, 'N', 'm_job 09', 'm_addr 09', sysdate, 09, 'N');
INSERT INTO tbl_member (m_id, m_pwd, m_name, m_nick, m_phone, m_email, m_birthdate, m_gender, m_job, m_addr, m_joindate, m_point, admin_yesno) VALUES ('m_id 10', 'm_pwd 10', 'm_name 10', 'm_nick 10', 'm_phone 10', 'm_email 10', sysdate, 'N', 'm_job 10', 'm_addr 10', sysdate, 10, 'N');




INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 001', 'article_subject 001', 'article_content 001', sysdate, 'm_id 001', 'article_file1 001', 'article_file2 001', 'article_file3 001', 'article_file4 001', 'article_file5 001', 001);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 002', 'article_subject 002', 'article_content 002', sysdate, 'm_id 002', 'article_file1 002', 'article_file2 002', 'article_file3 002', 'article_file4 002', 'article_file5 002', 002);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 003', 'article_subject 003', 'article_content 003', sysdate, 'm_id 003', 'article_file1 003', 'article_file2 003', 'article_file3 003', 'article_file4 003', 'article_file5 003', 003);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 004', 'article_subject 004', 'article_content 004', sysdate, 'm_id 004', 'article_file1 004', 'article_file2 004', 'article_file3 004', 'article_file4 004', 'article_file5 004', 004);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 005', 'article_subject 005', 'article_content 005', sysdate, 'm_id 005', 'article_file1 005', 'article_file2 005', 'article_file3 005', 'article_file4 005', 'article_file5 005', 005);




INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 006', 'article_subject 006', 'article_content 006', sysdate, 'm_id 006', 'article_file1 001', 'article_file2 006', 'article_file3 006', 'article_file4 006', 'article_file5 006', 006);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 007', 'article_subject 007', 'article_content 007', sysdate, 'm_id 007', 'article_file1 001', 'article_file2 007', 'article_file3 007', 'article_file4 007', 'article_file5 007', 007);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 008', 'article_subject 008', 'article_content 008', sysdate, 'm_id 008', 'article_file1 001', 'article_file2 008', 'article_file3 008', 'article_file4 008', 'article_file5 008', 008);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 009', 'article_subject 009', 'article_content 009', sysdate, 'm_id 009', 'article_file1 001', 'article_file2 009', 'article_file3 009', 'article_file4 009', 'article_file5 009', 009);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 010', 'article_subject 010', 'article_content 010', sysdate, 'm_id 010', 'article_file1 002', 'article_file2 010', 'article_file3 010', 'article_file4 010', 'article_file5 010', 010);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 011', 'article_subject 011', 'article_content 011', sysdate, 'm_id 011', 'article_file1 002', 'article_file2 011', 'article_file3 011', 'article_file4 011', 'article_file5 011', 011);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 012', 'article_subject 012', 'article_content 012', sysdate, 'm_id 012', 'article_file1 002', 'article_file2 012', 'article_file3 012', 'article_file4 012', 'article_file5 012', 012);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 013', 'article_subject 013', 'article_content 013', sysdate, 'm_id 013', 'article_file1 002', 'article_file2 013', 'article_file3 013', 'article_file4 013', 'article_file5 013', 013);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 014', 'article_subject 014', 'article_content 014', sysdate, 'm_id 014', 'article_file1 014', 'article_file2 014', 'article_file3 014', 'article_file4 014', 'article_file5 014', 014);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 015', 'article_subject 015', 'article_content 015', sysdate, 'm_id 015', 'article_file1 015', 'article_file2 015', 'article_file3 015', 'article_file4 015', 'article_file5 015', 015);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 016', 'article_subject 016', 'article_content 016', sysdate, 'm_id 016', 'article_file1 016', 'article_file2 016', 'article_file3 016', 'article_file4 016', 'article_file5 016', 016);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 017', 'article_subject 017', 'article_content 017', sysdate, 'm_id 017', 'article_file1 017', 'article_file2 017', 'article_file3 017', 'article_file4 017', 'article_file5 017', 017);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 018', 'article_subject 018', 'article_content 018', sysdate, 'm_id 018', 'article_file1 018', 'article_file2 018', 'article_file3 018', 'article_file4 018', 'article_file5 018', 018);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 019', 'article_subject 019', 'article_content 019', sysdate, 'm_id 019', 'article_file1 019', 'article_file2 019', 'article_file3 019', 'article_file4 019', 'article_file5 019', 019);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 020', 'article_subject 020', 'article_content 020', sysdate, 'm_id 020', 'article_file1 020', 'article_file2 020', 'article_file3 020', 'article_file4 020', 'article_file5 020', 020);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 021', 'article_subject 021', 'article_content 021', sysdate, 'm_id 021', 'article_file1 021', 'article_file2 021', 'article_file3 021', 'article_file4 021', 'article_file5 021', 021);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 022', 'article_subject 022', 'article_content 022', sysdate, 'm_id 022', 'article_file1 022', 'article_file2 022', 'article_file3 022', 'article_file4 022', 'article_file5 022', 022);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 023', 'article_subject 023', 'article_content 023', sysdate, 'm_id 023', 'article_file1 023', 'article_file2 023', 'article_file3 023', 'article_file4 023', 'article_file5 023', 023);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 024', 'article_subject 024', 'article_content 024', sysdate, 'm_id 024', 'article_file1 024', 'article_file2 024', 'article_file3 024', 'article_file4 024', 'article_file5 024', 024);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 025', 'article_subject 025', 'article_content 025', sysdate, 'm_id 025', 'article_file1 025', 'article_file2 025', 'article_file3 025', 'article_file4 025', 'article_file5 025', 025);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 026', 'article_subject 026', 'article_content 026', sysdate, 'm_id 026', 'article_file1 026', 'article_file2 026', 'article_file3 026', 'article_file4 026', 'article_file5 026', 026);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 027', 'article_subject 027', 'article_content 027', sysdate, 'm_id 027', 'article_file1 027', 'article_file2 027', 'article_file3 027', 'article_file4 027', 'article_file5 027', 027);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 028', 'article_subject 028', 'article_content 028', sysdate, 'm_id 028', 'article_file1 028', 'article_file2 028', 'article_file3 028', 'article_file4 028', 'article_file5 028', 028);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 029', 'article_subject 029', 'article_content 029', sysdate, 'm_id 029', 'article_file1 029', 'article_file2 029', 'article_file3 029', 'article_file4 029', 'article_file5 029', 029);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 030', 'article_subject 030', 'article_content 030', sysdate, 'm_id 030', 'article_file1 030', 'article_file2 030', 'article_file3 030', 'article_file4 030', 'article_file5 030', 030);




INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 031', 'article_subject 031', 'article_content 031', sysdate, 'm_id 031', 'article_file1 031', 'article_file2 031', 'article_file3 031', 'article_file4 031', 'article_file5 031', 031);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 032', 'article_subject 032', 'article_content 032', sysdate, 'm_id 032', 'article_file1 032', 'article_file2 032', 'article_file3 032', 'article_file4 032', 'article_file5 032', 032);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 033', 'article_subject 033', 'article_content 033', sysdate, 'm_id 033', 'article_file1 033', 'article_file2 033', 'article_file3 033', 'article_file4 033', 'article_file5 033', 033);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 034', 'article_subject 034', 'article_content 034', sysdate, 'm_id 034', 'article_file1 034', 'article_file2 034', 'article_file3 034', 'article_file4 034', 'article_file5 034', 034);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 035', 'article_subject 035', 'article_content 035', sysdate, 'm_id 035', 'article_file1 035', 'article_file2 035', 'article_file3 035', 'article_file4 035', 'article_file5 035', 035);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 036', 'article_subject 036', 'article_content 036', sysdate, 'm_id 036', 'article_file1 036', 'article_file2 036', 'article_file3 036', 'article_file4 036', 'article_file5 036', 036);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 037', 'article_subject 037', 'article_content 037', sysdate, 'm_id 037', 'article_file1 037', 'article_file2 037', 'article_file3 037', 'article_file4 037', 'article_file5 037', 037);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 038', 'article_subject 038', 'article_content 038', sysdate, 'm_id 038', 'article_file1 038', 'article_file2 038', 'article_file3 038', 'article_file4 038', 'article_file5 038', 038);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 039', 'article_subject 039', 'article_content 039', sysdate, 'm_id 039', 'article_file1 039', 'article_file2 039', 'article_file3 039', 'article_file4 039', 'article_file5 039', 039);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 040', 'article_subject 040', 'article_content 040', sysdate, 'm_id 040', 'article_file1 040', 'article_file2 040', 'article_file3 040', 'article_file4 040', 'article_file5 040', 040);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 041', 'article_subject 041', 'article_content 041', sysdate, 'm_id 041', 'article_file1 041', 'article_file2 041', 'article_file3 041', 'article_file4 041', 'article_file5 041', 041);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 042', 'article_subject 042', 'article_content 042', sysdate, 'm_id 042', 'article_file1 042', 'article_file2 042', 'article_file3 042', 'article_file4 042', 'article_file5 042', 042);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 043', 'article_subject 043', 'article_content 043', sysdate, 'm_id 043', 'article_file1 043', 'article_file2 043', 'article_file3 043', 'article_file4 043', 'article_file5 043', 043);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 044', 'article_subject 044', 'article_content 044', sysdate, 'm_id 044', 'article_file1 044', 'article_file2 044', 'article_file3 044', 'article_file4 044', 'article_file5 044', 044);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 045', 'article_subject 045', 'article_content 045', sysdate, 'm_id 045', 'article_file1 045', 'article_file2 045', 'article_file3 045', 'article_file4 045', 'article_file5 045', 045);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 046', 'article_subject 046', 'article_content 046', sysdate, 'm_id 046', 'article_file1 046', 'article_file2 046', 'article_file3 046', 'article_file4 046', 'article_file5 046', 046);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 047', 'article_subject 047', 'article_content 047', sysdate, 'm_id 047', 'article_file1 047', 'article_file2 047', 'article_file3 047', 'article_file4 047', 'article_file5 047', 047);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 048', 'article_subject 048', 'article_content 048', sysdate, 'm_id 048', 'article_file1 048', 'article_file2 048', 'article_file3 048', 'article_file4 048', 'article_file5 048', 048);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 049', 'article_subject 049', 'article_content 049', sysdate, 'm_id 049', 'article_file1 049', 'article_file2 049', 'article_file3 049', 'article_file4 049', 'article_file5 049', 049);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 050', 'article_subject 050', 'article_content 050', sysdate, 'm_id 050', 'article_file1 050', 'article_file2 050', 'article_file3 050', 'article_file4 050', 'article_file5 050', 050);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 051', 'article_subject 051', 'article_content 051', sysdate, 'm_id 051', 'article_file1 051', 'article_file2 051', 'article_file3 051', 'article_file4 051', 'article_file5 051', 051);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 052', 'article_subject 052', 'article_content 052', sysdate, 'm_id 052', 'article_file1 052', 'article_file2 052', 'article_file3 052', 'article_file4 052', 'article_file5 052', 052);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 053', 'article_subject 053', 'article_content 053', sysdate, 'm_id 053', 'article_file1 053', 'article_file2 053', 'article_file3 053', 'article_file4 053', 'article_file5 053', 053);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 054', 'article_subject 054', 'article_content 054', sysdate, 'm_id 054', 'article_file1 054', 'article_file2 054', 'article_file3 054', 'article_file4 054', 'article_file5 054', 054);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 055', 'article_subject 055', 'article_content 055', sysdate, 'm_id 055', 'article_file1 055', 'article_file2 055', 'article_file3 055', 'article_file4 055', 'article_file5 055', 055);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 056', 'article_subject 056', 'article_content 056', sysdate, 'm_id 056', 'article_file1 056', 'article_file2 056', 'article_file3 056', 'article_file4 056', 'article_file5 056', 056);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 057', 'article_subject 057', 'article_content 057', sysdate, 'm_id 057', 'article_file1 057', 'article_file2 057', 'article_file3 057', 'article_file4 057', 'article_file5 057', 057);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 058', 'article_subject 058', 'article_content 058', sysdate, 'm_id 058', 'article_file1 058', 'article_file2 058', 'article_file3 058', 'article_file4 058', 'article_file5 058', 058);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 059', 'article_subject 059', 'article_content 059', sysdate, 'm_id 059', 'article_file1 059', 'article_file2 059', 'article_file3 059', 'article_file4 059', 'article_file5 059', 059);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 060', 'article_subject 060', 'article_content 060', sysdate, 'm_id 060', 'article_file1 060', 'article_file2 060', 'article_file3 060', 'article_file4 060', 'article_file5 060', 060);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 061', 'article_subject 061', 'article_content 061', sysdate, 'm_id 061', 'article_file1 061', 'article_file2 061', 'article_file3 061', 'article_file4 061', 'article_file5 061', 061);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 062', 'article_subject 062', 'article_content 062', sysdate, 'm_id 062', 'article_file1 062', 'article_file2 062', 'article_file3 062', 'article_file4 062', 'article_file5 062', 062);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 063', 'article_subject 063', 'article_content 063', sysdate, 'm_id 063', 'article_file1 063', 'article_file2 063', 'article_file3 063', 'article_file4 063', 'article_file5 063', 063);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 064', 'article_subject 064', 'article_content 064', sysdate, 'm_id 064', 'article_file1 064', 'article_file2 064', 'article_file3 064', 'article_file4 064', 'article_file5 064', 064);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 065', 'article_subject 065', 'article_content 065', sysdate, 'm_id 065', 'article_file1 065', 'article_file2 065', 'article_file3 065', 'article_file4 065', 'article_file5 065', 065);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 066', 'article_subject 066', 'article_content 066', sysdate, 'm_id 066', 'article_file1 066', 'article_file2 066', 'article_file3 066', 'article_file4 066', 'article_file5 066', 066);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 067', 'article_subject 067', 'article_content 067', sysdate, 'm_id 067', 'article_file1 067', 'article_file2 067', 'article_file3 067', 'article_file4 067', 'article_file5 067', 067);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 068', 'article_subject 068', 'article_content 068', sysdate, 'm_id 068', 'article_file1 068', 'article_file2 068', 'article_file3 068', 'article_file4 068', 'article_file5 068', 068);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 069', 'article_subject 069', 'article_content 069', sysdate, 'm_id 069', 'article_file1 069', 'article_file2 069', 'article_file3 069', 'article_file4 069', 'article_file5 069', 069);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 070', 'article_subject 070', 'article_content 070', sysdate, 'm_id 070', 'article_file1 070', 'article_file2 070', 'article_file3 070', 'article_file4 070', 'article_file5 070', 070);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 071', 'article_subject 071', 'article_content 071', sysdate, 'm_id 071', 'article_file1 071', 'article_file2 071', 'article_file3 071', 'article_file4 071', 'article_file5 071', 071);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 072', 'article_subject 072', 'article_content 072', sysdate, 'm_id 072', 'article_file1 072', 'article_file2 072', 'article_file3 072', 'article_file4 072', 'article_file5 072', 072);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 073', 'article_subject 073', 'article_content 073', sysdate, 'm_id 073', 'article_file1 073', 'article_file2 073', 'article_file3 073', 'article_file4 073', 'article_file5 073', 073);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 074', 'article_subject 074', 'article_content 074', sysdate, 'm_id 074', 'article_file1 074', 'article_file2 074', 'article_file3 074', 'article_file4 074', 'article_file5 074', 074);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 075', 'article_subject 075', 'article_content 075', sysdate, 'm_id 075', 'article_file1 075', 'article_file2 075', 'article_file3 075', 'article_file4 075', 'article_file5 075', 075);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 076', 'article_subject 076', 'article_content 076', sysdate, 'm_id 076', 'article_file1 076', 'article_file2 076', 'article_file3 076', 'article_file4 076', 'article_file5 076', 076);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 077', 'article_subject 077', 'article_content 077', sysdate, 'm_id 077', 'article_file1 077', 'article_file2 077', 'article_file3 077', 'article_file4 077', 'article_file5 077', 077);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 078', 'article_subject 078', 'article_content 078', sysdate, 'm_id 078', 'article_file1 078', 'article_file2 078', 'article_file3 078', 'article_file4 078', 'article_file5 078', 078);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 079', 'article_subject 079', 'article_content 079', sysdate, 'm_id 079', 'article_file1 079', 'article_file2 079', 'article_file3 079', 'article_file4 079', 'article_file5 079', 079);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 080', 'article_subject 080', 'article_content 080', sysdate, 'm_id 080', 'article_file1 080', 'article_file2 080', 'article_file3 080', 'article_file4 080', 'article_file5 080', 080);



INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 081', 'article_subject 081', 'article_content 081', sysdate, 'm_id 081', 'article_file1 081', 'article_file2 081', 'article_file3 081', 'article_file4 081', 'article_file5 081', 081);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 082', 'article_subject 082', 'article_content 082', sysdate, 'm_id 082', 'article_file1 082', 'article_file2 082', 'article_file3 082', 'article_file4 082', 'article_file5 082', 082);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 083', 'article_subject 083', 'article_content 083', sysdate, 'm_id 083', 'article_file1 083', 'article_file2 083', 'article_file3 083', 'article_file4 083', 'article_file5 083', 083);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 084', 'article_subject 084', 'article_content 084', sysdate, 'm_id 084', 'article_file1 084', 'article_file2 084', 'article_file3 084', 'article_file4 084', 'article_file5 084', 084);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 085', 'article_subject 085', 'article_content 085', sysdate, 'm_id 085', 'article_file1 085', 'article_file2 085', 'article_file3 085', 'article_file4 085', 'article_file5 085', 085);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 086', 'article_subject 086', 'article_content 086', sysdate, 'm_id 086', 'article_file1 086', 'article_file2 086', 'article_file3 086', 'article_file4 086', 'article_file5 086', 086);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 087', 'article_subject 087', 'article_content 087', sysdate, 'm_id 087', 'article_file1 087', 'article_file2 087', 'article_file3 087', 'article_file4 087', 'article_file5 087', 087);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 088', 'article_subject 088', 'article_content 088', sysdate, 'm_id 088', 'article_file1 088', 'article_file2 088', 'article_file3 088', 'article_file4 088', 'article_file5 088', 088);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 089', 'article_subject 089', 'article_content 089', sysdate, 'm_id 089', 'article_file1 089', 'article_file2 089', 'article_file3 089', 'article_file4 089', 'article_file5 089', 089);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 090', 'article_subject 090', 'article_content 090', sysdate, 'm_id 090', 'article_file1 090', 'article_file2 090', 'article_file3 090', 'article_file4 090', 'article_file5 090', 090);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 091', 'article_subject 091', 'article_content 091', sysdate, 'm_id 091', 'article_file1 091', 'article_file2 091', 'article_file3 091', 'article_file4 091', 'article_file5 091', 091);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 092', 'article_subject 092', 'article_content 092', sysdate, 'm_id 092', 'article_file1 092', 'article_file2 092', 'article_file3 092', 'article_file4 092', 'article_file5 092', 092);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 093', 'article_subject 093', 'article_content 093', sysdate, 'm_id 093', 'article_file1 093', 'article_file2 093', 'article_file3 093', 'article_file4 093', 'article_file5 093', 093);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 094', 'article_subject 094', 'article_content 094', sysdate, 'm_id 094', 'article_file1 094', 'article_file2 094', 'article_file3 094', 'article_file4 094', 'article_file5 094', 094);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 095', 'article_subject 095', 'article_content 095', sysdate, 'm_id 095', 'article_file1 095', 'article_file2 095', 'article_file3 095', 'article_file4 095', 'article_file5 095', 095);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 096', 'article_subject 096', 'article_content 096', sysdate, 'm_id 096', 'article_file1 096', 'article_file2 096', 'article_file3 096', 'article_file4 096', 'article_file5 096', 096);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 097', 'article_subject 097', 'article_content 097', sysdate, 'm_id 097', 'article_file1 097', 'article_file2 097', 'article_file3 097', 'article_file4 097', 'article_file5 097', 097);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 098', 'article_subject 098', 'article_content 098', sysdate, 'm_id 098', 'article_file1 098', 'article_file2 098', 'article_file3 098', 'article_file4 098', 'article_file5 098', 098);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 099', 'article_subject 099', 'article_content 099', sysdate, 'm_id 099', 'article_file1 099', 'article_file2 099', 'article_file3 099', 'article_file4 099', 'article_file5 099', 099);
INSERT INTO tbl_nea (article_kind, article_subject, article_content, reg_date, m_id, article_file1, article_file2, article_file3, article_file4, article_file5, article_count) VALUES ('article_kind 100', 'article_subject 100', 'article_content 100', sysdate, 'm_id 100', 'article_file1 100', 'article_file2 100', 'article_file3 100', 'article_file4 100', 'article_file5 100', 100);


INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 11', 'chal_subject 11', 'chal_content 11', 'chal_period 11', 11, 11, 'chal_pic1 11', 'chal_pic2 11', 'chal_pic3 11', sysdate, 'm_id 11', 11, 'chal_pw 11', 'chal_public 11');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 12', 'chal_subject 12', 'chal_content 12', 'chal_period 12', 12, 12, 'chal_pic1 12', 'chal_pic2 12', 'chal_pic3 12', sysdate, 'm_id 12', 12, 'chal_pw 12', 'chal_public 12');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 13', 'chal_subject 13', 'chal_content 13', 'chal_period 13', 13, 13, 'chal_pic1 13', 'chal_pic2 13', 'chal_pic3 13', sysdate, 'm_id 13', 13, 'chal_pw 13', 'chal_public 13');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 14', 'chal_subject 14', 'chal_content 14', 'chal_period 14', 14, 14, 'chal_pic1 14', 'chal_pic2 14', 'chal_pic3 14', sysdate, 'm_id 14', 14, 'chal_pw 14', 'chal_public 14');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 15', 'chal_subject 15', 'chal_content 15', 'chal_period 15', 15, 15, 'chal_pic1 15', 'chal_pic2 15', 'chal_pic3 15', sysdate, 'm_id 15', 15, 'chal_pw 15', 'chal_public 15');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 16', 'chal_subject 16', 'chal_content 16', 'chal_period 16', 16, 16, 'chal_pic1 16', 'chal_pic2 16', 'chal_pic3 16', sysdate, 'm_id 16', 16, 'chal_pw 16', 'chal_public 16');




INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 17', 'chal_subject 17', 'chal_content 17', 'chal_period 17', 17, 17, 'chal_pic1 17', 'chal_pic2 17', 'chal_pic3 17', sysdate, 'm_id 17', 17, 'chal_pw 17', 'chal_public 17');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 18', 'chal_subject 18', 'chal_content 18', 'chal_period 18', 18, 18, 'chal_pic1 18', 'chal_pic2 18', 'chal_pic3 18', sysdate, 'm_id 18', 18, 'chal_pw 18', 'chal_public 18');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 19', 'chal_subject 19', 'chal_content 19', 'chal_period 19', 19, 19, 'chal_pic1 19', 'chal_pic2 19', 'chal_pic3 19', sysdate, 'm_id 19', 19, 'chal_pw 19', 'chal_public 19');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 20', 'chal_subject 20', 'chal_content 20', 'chal_period 20', 20, 20, 'chal_pic1 20', 'chal_pic2 20', 'chal_pic3 20', sysdate, 'm_id 20', 20, 'chal_pw 20', 'chal_public 20');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 21', 'chal_subject 21', 'chal_content 21', 'chal_period 21', 21, 21, 'chal_pic1 21', 'chal_pic2 21', 'chal_pic3 21', sysdate, 'm_id 21', 21, 'chal_pw 21', 'chal_public 21');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 22', 'chal_subject 22', 'chal_content 22', 'chal_period 22', 22, 22, 'chal_pic1 22', 'chal_pic2 22', 'chal_pic3 22', sysdate, 'm_id 22', 22, 'chal_pw 22', 'chal_public 22');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 23', 'chal_subject 23', 'chal_content 23', 'chal_period 23', 23, 23, 'chal_pic1 23', 'chal_pic2 23', 'chal_pic3 23', sysdate, 'm_id 23', 23, 'chal_pw 23', 'chal_public 23');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 24', 'chal_subject 24', 'chal_content 24', 'chal_period 24', 24, 24, 'chal_pic1 24', 'chal_pic2 24', 'chal_pic3 24', sysdate, 'm_id 24', 24, 'chal_pw 24', 'chal_public 24');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 25', 'chal_subject 25', 'chal_content 25', 'chal_period 25', 25, 25, 'chal_pic1 25', 'chal_pic2 25', 'chal_pic3 25', sysdate, 'm_id 25', 25, 'chal_pw 25', 'chal_public 25');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 26', 'chal_subject 26', 'chal_content 26', 'chal_period 26', 26, 26, 'chal_pic1 26', 'chal_pic2 26', 'chal_pic3 26', sysdate, 'm_id 26', 26, 'chal_pw 26', 'chal_public 26');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 27', 'chal_subject 27', 'chal_content 27', 'chal_period 27', 27, 27, 'chal_pic1 27', 'chal_pic2 27', 'chal_pic3 27', sysdate, 'm_id 27', 27, 'chal_pw 27', 'chal_public 27');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 28', 'chal_subject 28', 'chal_content 28', 'chal_period 28', 28, 28, 'chal_pic1 28', 'chal_pic2 28', 'chal_pic3 28', sysdate, 'm_id 28', 28, 'chal_pw 28', 'chal_public 28');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 29', 'chal_subject 29', 'chal_content 29', 'chal_period 29', 29, 29, 'chal_pic1 29', 'chal_pic2 29', 'chal_pic3 29', sysdate, 'm_id 29', 29, 'chal_pw 29', 'chal_public 29');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 30', 'chal_subject 30', 'chal_content 30', 'chal_period 30', 30, 30, 'chal_pic1 30', 'chal_pic2 30', 'chal_pic3 30', sysdate, 'm_id 30', 30, 'chal_pw 30', 'chal_public 30');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 31', 'chal_subject 31', 'chal_content 31', 'chal_period 31', 31, 31, 'chal_pic1 31', 'chal_pic2 31', 'chal_pic3 31', sysdate, 'm_id 31', 31, 'chal_pw 31', 'chal_public 31');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 32', 'chal_subject 32', 'chal_content 32', 'chal_period 32', 32, 32, 'chal_pic1 32', 'chal_pic2 32', 'chal_pic3 32', sysdate, 'm_id 32', 32, 'chal_pw 32', 'chal_public 32');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 33', 'chal_subject 33', 'chal_content 33', 'chal_period 33', 33, 33, 'chal_pic1 33', 'chal_pic2 33', 'chal_pic3 33', sysdate, 'm_id 33', 33, 'chal_pw 33', 'chal_public 33');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 34', 'chal_subject 34', 'chal_content 34', 'chal_period 34', 34, 34, 'chal_pic1 34', 'chal_pic2 34', 'chal_pic3 34', sysdate, 'm_id 34', 34, 'chal_pw 34', 'chal_public 34');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 35', 'chal_subject 35', 'chal_content 35', 'chal_period 35', 35, 35, 'chal_pic1 35', 'chal_pic2 35', 'chal_pic3 35', sysdate, 'm_id 35', 35, 'chal_pw 35', 'chal_public 35');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 36', 'chal_subject 36', 'chal_content 36', 'chal_period 36', 36, 36, 'chal_pic1 36', 'chal_pic2 36', 'chal_pic3 36', sysdate, 'm_id 36', 36, 'chal_pw 36', 'chal_public 36');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 37', 'chal_subject 37', 'chal_content 37', 'chal_period 37', 37, 37, 'chal_pic1 37', 'chal_pic2 37', 'chal_pic3 37', sysdate, 'm_id 37', 37, 'chal_pw 37', 'chal_public 37');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 38', 'chal_subject 38', 'chal_content 38', 'chal_period 38', 38, 38, 'chal_pic1 38', 'chal_pic2 38', 'chal_pic3 38', sysdate, 'm_id 38', 38, 'chal_pw 38', 'chal_public 38');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 39', 'chal_subject 39', 'chal_content 39', 'chal_period 39', 39, 39, 'chal_pic1 39', 'chal_pic2 39', 'chal_pic3 39', sysdate, 'm_id 39', 39, 'chal_pw 39', 'chal_public 39');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 40', 'chal_subject 40', 'chal_content 40', 'chal_period 40', 40, 40, 'chal_pic1 40', 'chal_pic2 40', 'chal_pic3 40', sysdate, 'm_id 40', 40, 'chal_pw 40', 'chal_public 40');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 41', 'chal_subject 41', 'chal_content 41', 'chal_period 41', 41, 41, 'chal_pic1 41', 'chal_pic2 41', 'chal_pic3 41', sysdate, 'm_id 41', 41, 'chal_pw 41', 'chal_public 41');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 42', 'chal_subject 42', 'chal_content 42', 'chal_period 42', 42, 42, 'chal_pic1 42', 'chal_pic2 42', 'chal_pic3 42', sysdate, 'm_id 42', 42, 'chal_pw 42', 'chal_public 42');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 43', 'chal_subject 43', 'chal_content 43', 'chal_period 43', 43, 43, 'chal_pic1 43', 'chal_pic2 43', 'chal_pic3 43', sysdate, 'm_id 43', 43, 'chal_pw 43', 'chal_public 43');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 44', 'chal_subject 44', 'chal_content 44', 'chal_period 44', 44, 44, 'chal_pic1 44', 'chal_pic2 44', 'chal_pic3 44', sysdate, 'm_id 44', 44, 'chal_pw 44', 'chal_public 44');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 45', 'chal_subject 45', 'chal_content 45', 'chal_period 45', 45, 45, 'chal_pic1 45', 'chal_pic2 45', 'chal_pic3 45', sysdate, 'm_id 45', 45, 'chal_pw 45', 'chal_public 45');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 46', 'chal_subject 46', 'chal_content 46', 'chal_period 46', 46, 46, 'chal_pic1 46', 'chal_pic2 46', 'chal_pic3 46', sysdate, 'm_id 46', 46, 'chal_pw 46', 'chal_public 46');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 47', 'chal_subject 47', 'chal_content 47', 'chal_period 47', 47, 47, 'chal_pic1 47', 'chal_pic2 47', 'chal_pic3 47', sysdate, 'm_id 47', 47, 'chal_pw 47', 'chal_public 47');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 48', 'chal_subject 48', 'chal_content 48', 'chal_period 48', 48, 48, 'chal_pic1 48', 'chal_pic2 48', 'chal_pic3 48', sysdate, 'm_id 48', 48, 'chal_pw 48', 'chal_public 48');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 49', 'chal_subject 49', 'chal_content 49', 'chal_period 49', 49, 49, 'chal_pic1 49', 'chal_pic2 49', 'chal_pic3 49', sysdate, 'm_id 49', 49, 'chal_pw 49', 'chal_public 49');
INSERT INTO tbl_challenge (chal_cat, chal_subject, chal_content, chal_period, chal_time, chal_point, chal_pic1, chal_pic2, chal_pic3, reg_date, m_id, chal_cnt, chal_pw, chal_public) VALUES ('chal_cat 50', 'chal_subject 50', 'chal_content 50', 'chal_period 50', 50, 50, 'chal_pic1 50', 'chal_pic2 50', 'chal_pic3 50', sysdate, 'm_id 50', 50, 'chal_pw 50', 'chal_public 50');
